// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import { BaselineAssessmentTool } from './BaselineAssessmentTool/BaselineAssessmentTool.js'

export const generatedSkillActionTools = [
  BaselineAssessmentTool,
] as const

export const generatedSkillActionToolNames = new Set(
  generatedSkillActionTools.map(tool => tool.name.toLowerCase()),
)
