import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod/v4'
import { parseFrontmatter } from '../src/utils/frontmatterParser.js'

export const GENERATED_FILE_MARKER =
  '// Generated by scripts/generate-skill-action-tools.ts. Do not edit.'

const skillNamePattern = /^[a-z0-9][a-z0-9-]{0,63}$/
const toolNamePattern = /^[A-Z][A-Za-z0-9]{0,63}$/
const inputNamePattern = /^[a-z_][a-z0-9_]*$/

const inputFieldSchema = z.strictObject({
  type: z.enum(['string', 'number', 'boolean', 'json']),
  required: z.boolean().optional().default(false),
  description: z.string().trim().min(1).optional(),
})

const actionToolConfigSchema = z.strictObject({
  tool_name: z.string().regex(toolNamePattern).optional(),
  user_facing_name: z.string().trim().min(1).optional(),
  search_hint: z.string().trim().min(1).optional(),
  preserve_existing: z.boolean().optional().default(false),
  always_load: z.boolean().optional().default(false),
  read_only: z.boolean().optional().default(true),
  input: z.record(z.string(), inputFieldSchema).optional(),
})

type ActionToolConfig = z.infer<typeof actionToolConfigSchema>
type ActionToolInputField = z.infer<typeof inputFieldSchema>

export type SkillActionToolSpec = {
  skillName: string
  toolName: string
  exportName: string
  description: string
  userFacingName: string
  searchHint?: string
  preserveExisting: boolean
  alwaysLoad: boolean
  readOnly: boolean
  input: Record<string, ActionToolInputField>
  skillDir: string
  outputFile: string
}

export type SkillActionToolPlanEntry = SkillActionToolSpec & {
  disposition: 'create' | 'update-generated' | 'preserve-existing'
}

export type SkillActionToolPlan = {
  entries: SkillActionToolPlanEntry[]
  registryFile: string
  registrySource: string
}

export type SkillActionToolFactoryOptions = {
  skillsDir: string
  toolsDir: string
  registryFile?: string
}

function titleCaseWords(value: string): string {
  return value
    .split(/[-_]+/)
    .filter(Boolean)
    .map(part => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('')
}

function humanizeSkillName(value: string): string {
  return value
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part, index) =>
      index === 0
        ? `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`
        : part,
    )
    .join(' ')
}

function validateInputFields(
  skillName: string,
  input: Record<string, ActionToolInputField>,
): void {
  for (const name of Object.keys(input)) {
    if (!inputNamePattern.test(name)) {
      throw new Error(
        `Skill ${skillName} has invalid action Tool input name ${JSON.stringify(name)}`,
      )
    }
  }
}

async function readOptionalConfig(skillDir: string): Promise<ActionToolConfig> {
  const configFile = join(skillDir, 'action-tool.json')
  try {
    const source = await readFile(configFile, 'utf8')
    return actionToolConfigSchema.parse(JSON.parse(source))
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return actionToolConfigSchema.parse({})
    }
    throw new Error(
      `Invalid action Tool config at ${configFile}: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
}

async function readExistingSource(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw error
  }
}

function defaultInput(): Record<string, ActionToolInputField> {
  return {
    request: {
      type: 'string',
      required: false,
      description:
        'Optional invocation-specific request. Relevant evidence remains in the forked conversation context.',
    },
  }
}

export async function discoverSkillActionTools(
  options: SkillActionToolFactoryOptions,
): Promise<SkillActionToolSpec[]> {
  const entries = await readdir(options.skillsDir, { withFileTypes: true })
  const specs: SkillActionToolSpec[] = []

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) continue

    const skillDir = join(options.skillsDir, entry.name)
    const skillFile = join(skillDir, 'SKILL.md')
    let source: string
    try {
      source = await readFile(skillFile, 'utf8')
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue
      throw error
    }

    const { frontmatter } = parseFrontmatter(source, skillFile)
    if (frontmatter['model-entry'] !== 'action-tool') continue

    const skillName = String(frontmatter.name ?? '').trim()
    const description = String(frontmatter.description ?? '').trim()
    if (!skillNamePattern.test(skillName)) {
      throw new Error(`Invalid action Skill name ${JSON.stringify(skillName)}`)
    }
    if (skillName !== entry.name) {
      throw new Error(
        `Action Skill directory ${entry.name} does not match frontmatter name ${skillName}`,
      )
    }
    if (!description) {
      throw new Error(`Action Skill ${skillName} must have a description`)
    }

    const config = await readOptionalConfig(skillDir)
    const toolName = config.tool_name ?? titleCaseWords(skillName)
    if (!toolNamePattern.test(toolName)) {
      throw new Error(`Invalid generated Tool name ${JSON.stringify(toolName)}`)
    }
    const input = config.input ?? defaultInput()
    validateInputFields(skillName, input)

    const exportName = `${toolName}Tool`
    specs.push({
      skillName,
      toolName,
      exportName,
      description,
      userFacingName:
        config.user_facing_name ?? humanizeSkillName(skillName),
      searchHint: config.search_hint,
      preserveExisting: config.preserve_existing,
      alwaysLoad: config.always_load,
      readOnly: config.read_only,
      input,
      skillDir,
      outputFile: join(options.toolsDir, exportName, `${exportName}.ts`),
    })
  }

  const byToolName = new Map<string, string>()
  for (const spec of specs) {
    const previous = byToolName.get(spec.toolName)
    if (previous) {
      throw new Error(
        `Action Skills ${previous} and ${spec.skillName} map to the same Tool name ${spec.toolName}`,
      )
    }
    byToolName.set(spec.toolName, spec.skillName)
  }

  return specs
}

function renderZodField(field: ActionToolInputField): string {
  const base =
    field.type === 'string'
      ? 'z.string().trim().min(1)'
      : field.type === 'number'
        ? 'z.number()'
        : field.type === 'boolean'
          ? 'z.boolean()'
          : 'z.json()'
  const described = field.description
    ? `${base}.describe(${JSON.stringify(field.description)})`
    : base
  return field.required ? described : `${described}.optional()`
}

export function renderSkillActionTool(spec: SkillActionToolSpec): string {
  const inputFields = Object.entries(spec.input)
    .map(([name, field]) => `    ${name}: ${renderZodField(field)},`)
    .join('\n')
  const searchHint = spec.searchHint
    ? `\n  searchHint: ${JSON.stringify(spec.searchHint)},`
    : ''
  const userFacingName = JSON.stringify(spec.userFacingName)
  const useMessage = JSON.stringify(`Run ${spec.userFacingName}`)
  const rejectedMessage = JSON.stringify(`${spec.userFacingName} rejected`)
  const failedMessage = JSON.stringify(`${spec.userFacingName} failed`)
  const progressMessage = JSON.stringify(`Running ${spec.userFacingName}`)

  return `${GENERATED_FILE_MARKER}
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = ${JSON.stringify(spec.skillName)} as const

const inputSchema = lazySchema(() =>
  z.strictObject({
${inputFields}
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const ${spec.exportName} = buildTool({
  name: ${JSON.stringify(spec.toolName)},${searchHint}
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: ${spec.alwaysLoad},
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return ${userFacingName}
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return ${spec.readOnly}
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return ${useMessage}
  },
  renderToolUseRejectedMessage() {
    return ${rejectedMessage}
  },
  renderToolUseErrorMessage() {
    return ${failedMessage}
  },
  renderToolUseProgressMessage() {
    return ${progressMessage}
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
`
}

export function renderSkillActionToolRegistry(
  specs: readonly SkillActionToolSpec[],
  registryFile: string,
): string {
  const imports = specs
    .map(spec => {
      const modulePath = `./${relative(dirname(registryFile), spec.outputFile)
        .replaceAll('\\', '/')
        .replace(/\.ts$/, '.js')}`
      return `import { ${spec.exportName} } from ${JSON.stringify(modulePath)}`
    })
    .join('\n')
  const exports = specs.map(spec => `  ${spec.exportName},`).join('\n')

  return `${GENERATED_FILE_MARKER}
${imports}${imports ? '\n\n' : ''}export const generatedSkillActionTools = [
${exports}
] as const

export const generatedSkillActionToolNames = new Set(
  generatedSkillActionTools.map(tool => tool.name.toLowerCase()),
)
`
}

export async function buildSkillActionToolPlan(
  options: SkillActionToolFactoryOptions,
): Promise<SkillActionToolPlan> {
  const specs = await discoverSkillActionTools(options)
  const entries: SkillActionToolPlanEntry[] = []

  for (const spec of specs) {
    const existing = await readExistingSource(spec.outputFile)
    if (
      existing !== null &&
      !existing.startsWith(GENERATED_FILE_MARKER) &&
      !spec.preserveExisting
    ) {
      throw new Error(
        `Refusing to overwrite non-generated Tool ${spec.outputFile}; set preserve_existing only when it is the intended implementation for ${spec.skillName}`,
      )
    }
    if (
      existing !== null &&
      spec.preserveExisting &&
      !existing.includes(`export const ${spec.exportName}`)
    ) {
      throw new Error(
        `Existing Tool ${spec.outputFile} does not export ${spec.exportName}`,
      )
    }
    const disposition =
      existing === null
        ? 'create'
        : existing.startsWith(GENERATED_FILE_MARKER)
          ? 'update-generated'
          : 'preserve-existing'
    entries.push({ ...spec, disposition })
  }

  const registryFile =
    options.registryFile ?? join(options.toolsDir, 'generatedSkillActionTools.ts')
  const existingRegistry = await readExistingSource(registryFile)
  if (
    existingRegistry !== null &&
    !existingRegistry.startsWith(GENERATED_FILE_MARKER)
  ) {
    throw new Error(`Refusing to overwrite non-generated registry ${registryFile}`)
  }
  return {
    entries,
    registryFile,
    registrySource: renderSkillActionToolRegistry(entries, registryFile),
  }
}

export async function writeSkillActionToolPlan(
  plan: SkillActionToolPlan,
): Promise<void> {
  for (const entry of plan.entries) {
    if (entry.disposition === 'preserve-existing') continue
    await mkdir(dirname(entry.outputFile), { recursive: true })
    await writeFile(entry.outputFile, renderSkillActionTool(entry), 'utf8')
  }
  await mkdir(dirname(plan.registryFile), { recursive: true })
  await writeFile(plan.registryFile, plan.registrySource, 'utf8')
}

function readFlagValue(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag)
  return index === -1 ? undefined : args[index + 1]
}

async function main(): Promise<void> {
  const scriptDir = dirname(fileURLToPath(import.meta.url))
  const backendDir = resolve(scriptDir, '..')
  const projectRoot = resolve(backendDir, '../..')
  const args = process.argv.slice(2)
  const options: SkillActionToolFactoryOptions = {
    skillsDir: resolve(readFlagValue(args, '--skills-dir') ?? join(projectRoot, 'skills')),
    toolsDir: resolve(readFlagValue(args, '--tools-dir') ?? join(backendDir, 'src/tools')),
  }
  const plan = await buildSkillActionToolPlan(options)
  const write = args.includes('--write')
  if (write) await writeSkillActionToolPlan(plan)

  process.stdout.write(
    `${JSON.stringify(
      {
        mode: write ? 'write' : 'plan',
        registry_file: plan.registryFile,
        tools: plan.entries.map(entry => ({
          skill_name: entry.skillName,
          tool_name: entry.toolName,
          output_file: entry.outputFile,
          disposition: entry.disposition,
        })),
      },
      null,
      2,
    )}\n`,
  )
}

if (import.meta.main) {
  await main()
}
